#!/bin/bash

set -eux # -x for verbose logging to juju debug-log
hooksdir=$PWD
juju-log "Installing rubygems and puppet"
apt-get update
apt-get -y install rubygems unzip
gem install --no-rdoc --no-ri --version=2.7.20 puppet
apt-get install libgpgme11-dev make -y
gem install --no-rdoc --no-ri hiera hiera-puppet rake
wget https://github.com/glennpratt/hiera-gpg/raw/allplayers/pkg/hiera-gpg-1.1.1.gem
gem install --no-rdoc --no-ri hiera-gpg-1.1.1.gem

juju-log "Hack: Getting puppet files into place"
mkdir -p /etc/puppet
unzip $hooksdir/data/Puppet.zip
rm -rf /etc/puppet
mv Puppet /etc/puppet

juju-log "Hack: Forcing fqdn with"
touch /etc/puppet/hieradata/fqdn/`unit-get private-address`.yaml
sed -e "s/base_url:.*/base_url: `unit-get public-address`/g" /etc/puppet/hieradata/fqdn/a.cchristensen.allplayers.com.yaml > /etc/puppet/hieradata/fqdn/`unit-get private-address`.yaml

juju-log "Running Puppet apply (a couple of times?) to deploy onto the machine."
cd /etc/puppet
puppet apply /etc/puppet/manifests/site.pp --debug --verbose --external_nodes=/etc/puppet/nodes_extlookup.rb --confdir=/etc/puppet --node_terminus=exec --environment=development
open-port 80/tcp
